import dotenv from "dotenv";

dotenv.config({ quiet: true });

const ENV = {
  PORT: process.env.PORT || "5001",
  DB_URL: process.env.DB_URL,
  NODE_ENV: process.env.NODE_ENV || "development",
  CLIENT_URL: process.env.CLIENT_URL,
  PISTON_API_URL: process.env.PISTON_API_URL,
  PISTON_AUTH_HEADER: process.env.PISTON_AUTH_HEADER,
  PISTON_AUTH_TOKEN: process.env.PISTON_AUTH_TOKEN,
  CODE_EXECUTION_TIMEOUT_MS: process.env.CODE_EXECUTION_TIMEOUT_MS || "20000",
  CODE_EXECUTION_MAX_CODE_SIZE: process.env.CODE_EXECUTION_MAX_CODE_SIZE || "20000",
  CODE_EXECUTION_RATE_LIMIT_MAX: process.env.CODE_EXECUTION_RATE_LIMIT_MAX || "30",
  CODE_EXECUTION_RATE_LIMIT_WINDOW_MS:
    process.env.CODE_EXECUTION_RATE_LIMIT_WINDOW_MS || "60000",
  INNGEST_EVENT_KEY: process.env.INNGEST_EVENT_KEY,
  INNGEST_SIGNING_KEY: process.env.INNGEST_SIGNING_KEY,
  STREAM_API_KEY: process.env.STREAM_API_KEY,
  STREAM_API_SECRET: process.env.STREAM_API_SECRET,
};

export default ENV;
